# Generated by Django 5.1.3 on 2024-11-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0001_initial"),
        ("users", "0003_userorganization_userorganizationmission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.IntegerField()),
                ("qr_code", models.ImageField(upload_to="qr_codes/")),
                ("scanned", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.mission",
                    ),
                ),
                (
                    "user_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.userorganization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
