# Generated by Django 5.1.3 on 2024-11-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("limit", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="mission_images/"
                    ),
                ),
                ("points", models.IntegerField(blank=True, default=0, null=True)),
                ("goal", models.IntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("basic", "Basic"),
                            ("advanced", "Advanced"),
                            ("vip", "VIP"),
                        ],
                        default="basic",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                            ("inactive", "Inactive"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "rewards",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="mission_rewards",
                        to="rewards.reward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
