# Generated by Django 5.1.3 on 2024-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="rewards",
            field=models.ManyToManyField(
                blank=True, related_name="mission_rewards", to="rewards.reward"
            ),
        ),
    ]
