# Generated by Django 5.1.3 on 2024-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_alter_mission_rewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="finished_times",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
